source 'https://github.com/CocoaPods/Specs.git'

target 'UIBezierPath-RoundedPolygon' do
  pod "UIBezierPath-RoundedPolygon", :path => "../"
end

target 'Tests' do
  pod "UIBezierPath-RoundedPolygon", :path => "../"
end
